MentorTeamSync/teamsync_Infosys_Internship_Oct2024

client/package-lock.json, client/package.json, client/src/api/index.js, client/src/components/OTP.jsx, client/src/components/SignIn.jsx, client/src/components/SignUp.jsx, client/src/index.js, client/src/pages/Home/Home.jsx, client/src/redux/snackbarSlice.js, client/src/redux/store.js, client/src/redux/userSlice.js
This pull request implements the sign-up and sign-in functionality to enhance user authentication within the application. These features provide users with a streamlined process to create an account and access their profiles.
- **Sign-In Component**: Developed a user-friendly interface for users to log into their accounts.
- **Sign-Up Component**: Created a registration form that captures essential user information for account creation.
- **Responsive Design**: Ensured both components are fully responsive for optimal viewing on various devices.
- **Navigation Updates**: Updated the navigation bar to include links to the sign-in and sign-up pages.
- Utilized **React** for building the components.
- Employed **styled-components** for scoped styling and improved maintainability.
- Integrated …
=> Feat : Sign-Up and Sign-In Features

backend/middlewares/UserMiddlewares.js, backend/routes/user.js, client/src/components/OTP.jsx, package-lock.json, package.json, tailwind.config.js
=> Issue : #25 added necesary comments

client/src/pages/Home/components/Benifits.jsx
Noticed some icons in benefit section are floating outside the wrapper.
=> Update Benifits.jsx to adjust the position of some icons.

client/src/pages/Home/components/Benifits.jsx
Issue #27 is resolved in benefits section by changing the position of id.
=> Updated Benifits.jsx in order to resolve Issue #27 

client/src/pages/Home/components/Features.jsx
The feature section also changed in order to avoid overflow. Issue : #27 is resolved successfully.
=> Update Features.jsx Issue : #27 is resolved here

client/src/components/SignUp.jsx
=> Issue #33 : Changed error fetching mechanism as per backend api response

client/src/components/SignUp.jsx
=> Issue #32 resolved proper error messages on signup

client/src/components/SignIn.jsx
Reverts MentorTeamSync/teamsync_Infosys_Internship_Oct2024#38
=> Revert "Ratikanta"

backend/db/index.js, client/src/pages/Dashboard/Dashboard.jsx, client/src/pages/Dashboard/components/Hero.jsx, client/src/pages/Dashboard/components/ProjectTable.jsx, client/src/pages/Dashboard/components/Sidebar.jsx, client/src/pages/Dashboard/components/common/ProgressBar.jsx, client/src/pages/Dashboard/components/table/ProjectRow.jsx
=> made dashboard reponsive:

client/src/pages/Home/components/Navbar.jsx
=> bug fix menu item animation improved.

client/src/pages/Home/Home.jsx, client/src/pages/Home/components/Hero.jsx, client/src/pages/Home/components/Navbar.jsx
=> Issue #45 resolved

client/src/pages/Home/components/Faq.jsx, client/src/pages/Home/components/Navbar.jsx
=> Issue #54 resolved , removed home and added faqs

client/src/pages/Home/components/Navbar.jsx
=> Issue #56 solved

backend/db/index.js, backend/middlewares/ProjectMiddlewares.js, backend/routes/project.js, client/src/pages/Dashboard/project-dashboard/components/ProjectTable.jsx, client/src/pages/Dashboard/project-dashboard/components/table/ProjectRow.jsx
=> Shubham patel

backend/middlewares/UserMiddlewares.js, backend/routes/user.js, client/src/components/OTP.jsx, client/src/components/SignIn.jsx, client/src/pages/Dashboard/profile/components/Sidebar.jsx, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx
=> Issue #99 resolved fully

client/src/pages/Dashboard/admin-dashboard/components/Sidebar.jsx, client/src/pages/Dashboard/profile/components/Sidebar.jsx, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx
=> Issue #96 fully resolved

client/src/pages/Dashboard/admin-dashboard/components/Sidebar.jsx, client/src/pages/Dashboard/profile/components/Sidebar.jsx, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx, client/src/pages/Home/components/Navbar.jsx
=> Issue #19 resolved

client/src/pages/Dashboard/profile/components/table/ProjectRow.jsx
=> Fully resolved Issue #105

backend/middlewares/ProjectMiddlewares.js, backend/routes/project.js, client/src/pages/Dashboard/project-dashboard/components/project/AddProjectModal.jsx, client/src/pages/Dashboard/project-dashboard/components/table/ProjectRow.jsx, client/src/pages/Dashboard/project-dashboard/components/table/TableHeader.jsx
=> Issue #109 resolved

backend/middlewares/TaskMiddlewares.js, backend/routes/task.js
details that can be edited are the task description and priority
=> added edit details of a task

backend/middlewares/TaskMiddlewares.js, backend/routes/task.js
added backend to update status, delete task from the project and backend for getting the tasks created by user and tasks assigned to the user
=> added backend for update status, delete task and get user tasks

client/src/pages/Dashboard/profile/components/table/ProjectRow.jsx
Updated ProjectRow component to include logic for displaying and fetching members. Enhanced the "Add Users" modal to grey out users who are already part of the project or have been selected, improving clarity and user experience. 
Issue: #120
=> Add member logic & grey out selected users in modal

client/src/pages/Dashboard/profile/components/table/ProjectRow.jsx
Implemented an "Edit Deadline" button in the Project Row component, allowing users to update project deadlines directly from the UI.
Issue: #124
=> Add Edit Deadline Button to ProjectRow

backend/middlewares/TaskMiddlewares.js, backend/routes/task.js
combined update deadline, update status into edit details backend
=> updating backend for edit task details

backend/db/index.js, backend/middlewares/TaskMiddlewares.js, client/src/pages/Dashboard/my-tasks/MyTasksTable.jsx, client/src/pages/Dashboard/project-view/task/AddTaskModal.jsx
=> Issue #136 resolved

backend/middlewares/TaskMiddlewares.js, client/src/pages/Dashboard/project-view/table/TaskTable.jsx
=> Issue #135 resolved

client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx
=> Issue #142 resolved by truncating above 16 length

client/src/pages/Dashboard/project-dashboard/components/table/MyProjectRow.jsx
=> Issue #144 resolved

backend/middlewares/ProjectMiddlewares.js, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx, client/src/pages/Home/components/Hero.jsx, client/src/pages/Home/components/Navbar.jsx
=> Issue #146 and other small bugs resolved

client/src/pages/Dashboard/profile/ProfileModal.jsx, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx, package-lock.json, package.json
=> Issue #151 resolved byadding profile modal popup

backend/middlewares/TaskMiddlewares.js, client/package-lock.json, client/package.json, client/src/pages/Dashboard/my-tasks/MyTasksTable.jsx, client/src/pages/Dashboard/project-view/table/TaskTable.jsx, client/yarn.lock
=> Issue #161 resolved

client/src/pages/Dashboard/project-dashboard/components/table/ProjectRow.jsx, client/src/pages/Dashboard/project-view/task/AddTaskModal.jsx
=> Issue #169 resolved

backend/middlewares/TaskMiddlewares.js, backend/routes/task.js, client/src/pages/Dashboard/my-tasks/MyTasksTable.jsx, client/src/pages/Dashboard/project-dashboard/components/Hero.jsx, client/src/pages/Dashboard/project-dashboard/components/Sidebar.jsx
Resolves #174 by changing task fetching backend route based on params
=> Issue #174 resolved

backend/middlewares/TaskMiddlewares.js, client/src/pages/Dashboard/my-tasks/MyTasksTable.jsx, client/src/pages/Dashboard/project-view/table/TaskTable.jsx
=> Issue #180 resolved

client/src/pages/Dashboard/project-view/components/ChatModal.jsx
This update optimizes the ChatModal component by enhancing its reactivity for a smoother user experience. It also introduces an "Add Media" button, allowing users to upload images and videos along with their messages.
=> Optimize ChatModal: improve reactivity and add 'Add Media' functionality. 

client/src/pages/Home/components/Navbar.jsx, client/yarn.lock
Added dashboard button and testimonials in navbar for easy access
=> Modified Home page

client/src/pages/Dashboard/project-view/components/ChatModal.jsx
This PR adjusts the position and shape of the chat modal. The width has been decreased for a more compact design, and the height has been increased for better visibility of messages. These changes improve the overall layout and user experience.
#205
=> Adjust Chat Modal Position, Width, and Height

client/src/pages/Dashboard/project-view/components/ChatModal.jsx
Refactor chat modal for better responsiveness, UI, and media display, including adjustments to button sizes, container height, and styling.
Issue: #207
=> Refactor chat modal layout and style to improve responsiveness and UI

client/src/pages/Dashboard/project-view/components/ChatModal.jsx, client/yarn.lock
This update stops the chat from automatically scrolling to the bottom when reacting to messages with like or dislike. The chat will now only scroll down when a new message is sent.
Issue: #215 #213
=> Prevent Auto-Scroll on Message Reactions in Chat Modal

client/src/pages/Dashboard/project-view/components/ChatModal.jsx, client/yarn.lock
I modified useremail in chatbox to username to display on head.
This modification dont change the message head of previous messages
=> Updated chatmodel to display username

client/src/pages/Dashboard/project-view/components/ChatModal.jsx
Refine the chat modal theme for a more professional and polished appearance. Update button styling and enhance the overall UI for improved user experience and visual consistency.
=> Refine chat modal theme

client/src/pages/Dashboard/project-view/components/ChatModal.jsx
Implement a toggle feature for the ChatModal, allowing it to open and close when the button is clicked. Fetch messages when the modal opens, and handle message scrolling smoothly during updates.
=> Add toggle functionality for ChatModal component

client/src/pages/Dashboard/project-view/task/AddTaskModal.jsx
Aligns button color with theme for a cohesive look.
=> Change button color to match theme

client/src/pages/Dashboard/project-view/table/TaskTable.jsx
Update SearchBar and dropdown modals to match consistent theme styling.
=> Update button theme to match SearchBar styling

client/src/profilepage.js, client/src/profilephoto.js
Integrate profile photo instead of avatar
=> Integrate profile photo instead of avatar

client/src/pages/Dashboard/project-view/components/ChatModal.jsx, client/src/pages/Dashboard/project-view/components/ReplyBox.jsx
- Added clear and informative error messages to improve user experience during file upload and download failures in the Scholarship Portal.
- Ensured users receive specific feedback for file operation issues to assist with troubleshooting.
- Improved overall error handling to provide a more intuitive and smooth experience when encountering file-related issues.
=> Enhance error handling with user-friendly messages for file upload/download failures

backend/controllers/NotificationController.js, backend/db/index.js, backend/routes/comment.js
trigger for incrementing the unread messages count, routes to get the unread messages count project and total.
=> backend for notifications (get routes)

client/src/pages/Dashboard/project-view/table/TaskTable.jsx
Filters out completed tasks from being displayed in the tasks table for assigned projects, ensuring that only active tasks are shown.
=> Exclude Completed Tasks from Tasks Table in Assigned Projects Section

client/src/pages/Dashboard/project-dashboard/components/UsersProject.jsx, client/src/pages/Dashboard/project-dashboard/components/common/userSearchBar.jsx
changed placeholder from projects to user
=> Modified seachbar in user

client/src/App.js
Reverts MentorTeamSync/teamsync_Infosys_Internship_Oct2024#250
=> Revert "Update App.js"
